#!/bin/sh

#xmodmap $HOME/.Xmodmap &
fbsetbg -f images/default.jpg &
permutar dunst&

if ! pidof fbpanel > /dev/null; then
    echo "Iniciando fbpanel" >> ~/.mensajes
    fbpanel &
fi

#if ! pidof sonata > /dev/null; then
#    echo "Iniciando Sonata" >> ~/.mensajes
#    sonata --hidden&
#fi

dvorak

if ! pidof keynav > /dev/null; then
    echo "Iniciando keynav" >> ./mensajes
    keynav > /dev/null &
fi

if ! pidof vubat > /dev/null; then
    echo "Iniciando power-manager" >> ./mensajes
    sleep 5; vubat > /dev/null &
fi

#if ! pidof xfce4-power-manager > /dev/null; then
#    echo "Iniciando power-manager" >> ./mensajes
#    xfce4-power-manager &
#fi

#if ! pidof tomighty > /dev/null; then
#    echo "Iniciando gestor de pomodoros" >> ~/.mensajes
#    ~/bin/tomighty &
#fi

#if ! pidof xscreensaver > /dev/null; then
#    echo "Iniciando xcreensaver" >> ~/.mensajes
#    xscreensaver -no-splash&
#else
#    echo "Reiniciando xscreensaver" >> ~/.mensajes
#    killall xscreensaver
#    xscreensaver -no-splash&
#fi

if ! pidof dropbox > /dev/null; then
    echo "Iniciando dropbox" >> ~/.mensajes
    dropbox start -i&
fi
